### ISSUE TITLE
1.18 is not supported

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [SpongePowered/VanillaGradle#64]
When I try to build my project with Minecraft 1.18, 1.18.1 or 1.18.2, it fails with this error:
```
> Configure project :
Targeting Minecraft '1.18.2' on a 'SERVER' platform
Preparing Minecraft: Java Edition SERVER version 1.18.2
Failed to resolve Minecraft SERVER version 1.18.2:
java.lang.RuntimeException: java.lang.UnsupportedOperationException: Record requires ASM8
	at org.cadixdev.atlas.jar.JarFile.transform(JarFile.java:223)
	at org.cadixdev.atlas.Atlas.run(Atlas.java:150)
	at org.cadixdev.atlas.Atlas.run(Atlas.java:120)
	at org.spongepowered.gradle.vanilla.repository.MinecraftResolverImpl.lambda$provide$4(MinecraftResolverImpl.java:208)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.UnsupportedOperationException: Record requires ASM8
	at org.objectweb.asm.ClassVisitor.visitRecordComponent(ClassVisitor.java:305)
	at org.objectweb.asm.ClassReader.readRecordComponent(ClassReader.java:930)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:708)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.cadixdev.bombe.asm.analysis.ClassProviderInheritanceProvider.provide(ClassProviderInheritanceProvider.java:81)
	at org.cadixdev.bombe.analysis.InheritanceProvider.provide(InheritanceProvider.java:77)
	at org.cadixdev.lorenz.model.ClassMapping.provideInheritance(ClassMapping.java:480)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.complete(InheritanceCompletable.java:83)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.complete(InheritanceCompletable.java:68)
	at org.cadixdev.lorenz.asm.LorenzRemapper.getCompletedClassMapping(LorenzRemapper.java:73)
	at org.cadixdev.lorenz.asm.LorenzRemapper.mapFieldName(LorenzRemapper.java:79)
	at org.objectweb.asm.commons.MethodRemapper.visitFieldInsn(MethodRemapper.java:150)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2421)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:721)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.cadixdev.bombe.asm.jar.JarEntryRemappingTransformer.transform(JarEntryRemappingTransformer.java:75)
	at org.cadixdev.bombe.jar.JarClassEntry.accept(JarClassEntry.java:62)
	at org.cadixdev.bombe.jar.JarClassEntry.accept(JarClassEntry.java:39)
	at org.cadixdev.atlas.jar.JarFile.lambda$transform$3(JarFile.java:188)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	... 5 more
Failed to resolve Minecraft SERVER version 1.18.2:
java.lang.RuntimeException: java.lang.UnsupportedOperationException: Record requires ASM8
	at org.cadixdev.atlas.jar.JarFile.transform(JarFile.java:223)
	at org.cadixdev.atlas.Atlas.run(Atlas.java:150)
	at org.cadixdev.atlas.Atlas.run(Atlas.java:120)
	at org.spongepowered.gradle.vanilla.repository.MinecraftResolverImpl.lambda$provide$4(MinecraftResolverImpl.java:208)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.UnsupportedOperationException: Record requires ASM8
	at org.objectweb.asm.ClassVisitor.visitRecordComponent(ClassVisitor.java:305)
	at org.objectweb.asm.ClassReader.readRecordComponent(ClassReader.java:930)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:708)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.cadixdev.bombe.asm.analysis.ClassProviderInheritanceProvider.provide(ClassProviderInheritanceProvider.java:81)
	at org.cadixdev.bombe.analysis.InheritanceProvider.provide(InheritanceProvider.java:77)
	at org.cadixdev.lorenz.model.ClassMapping.provideInheritance(ClassMapping.java:480)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.complete(InheritanceCompletable.java:83)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.complete(InheritanceCompletable.java:68)
	at org.cadixdev.lorenz.asm.LorenzRemapper.getCompletedClassMapping(LorenzRemapper.java:73)
	at org.cadixdev.lorenz.asm.LorenzRemapper.mapFieldName(LorenzRemapper.java:79)
	at org.objectweb.asm.commons.MethodRemapper.visitFieldInsn(MethodRemapper.java:150)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2421)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:721)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.cadixdev.bombe.asm.jar.JarEntryRemappingTransformer.transform(JarEntryRemappingTransformer.java:75)
	at org.cadixdev.bombe.jar.JarClassEntry.accept(JarClassEntry.java:62)
	at org.cadixdev.bombe.jar.JarClassEntry.accept(JarClassEntry.java:39)
	at org.cadixdev.atlas.jar.JarFile.lambda$transform$3(JarFile.java:188)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	... 5 more
Failed to resolve Minecraft SERVER version 1.18.2:
java.lang.RuntimeException: java.lang.UnsupportedOperationException: Record requires ASM8
	at org.cadixdev.atlas.jar.JarFile.transform(JarFile.java:223)
	at org.cadixdev.atlas.Atlas.run(Atlas.java:150)
	at org.cadixdev.atlas.Atlas.run(Atlas.java:120)
	at org.spongepowered.gradle.vanilla.repository.MinecraftResolverImpl.lambda$provide$4(MinecraftResolverImpl.java:208)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.UnsupportedOperationException: Record requires ASM8
	at org.objectweb.asm.ClassVisitor.visitRecordComponent(ClassVisitor.java:305)
	at org.objectweb.asm.ClassReader.readRecordComponent(ClassReader.java:930)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:708)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.cadixdev.bombe.asm.analysis.ClassProviderInheritanceProvider.provide(ClassProviderInheritanceProvider.java:81)
	at org.cadixdev.bombe.analysis.InheritanceProvider.provide(InheritanceProvider.java:77)
	at org.cadixdev.lorenz.model.ClassMapping.provideInheritance(ClassMapping.java:480)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.complete(InheritanceCompletable.java:83)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.complete(InheritanceCompletable.java:68)
	at org.cadixdev.lorenz.asm.LorenzRemapper.getCompletedClassMapping(LorenzRemapper.java:73)
	at org.cadixdev.lorenz.asm.LorenzRemapper.mapFieldName(LorenzRemapper.java:79)
	at org.objectweb.asm.commons.MethodRemapper.visitFieldInsn(MethodRemapper.java:150)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2421)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:721)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.cadixdev.bombe.asm.jar.JarEntryRemappingTransformer.transform(JarEntryRemappingTransformer.java:75)
	at org.cadixdev.bombe.jar.JarClassEntry.accept(JarClassEntry.java:62)
	at org.cadixdev.bombe.jar.JarClassEntry.accept(JarClassEntry.java:39)
	at org.cadixdev.atlas.jar.JarFile.lambda$transform$3(JarFile.java:188)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	... 5 more
Failed to resolve Minecraft SERVER version 1.18.2:
java.lang.RuntimeException: java.lang.UnsupportedOperationException: Record requires ASM8
	at org.cadixdev.atlas.jar.JarFile.transform(JarFile.java:223)
	at org.cadixdev.atlas.Atlas.run(Atlas.java:150)
	at org.cadixdev.atlas.Atlas.run(Atlas.java:120)
	at org.spongepowered.gradle.vanilla.repository.MinecraftResolverImpl.lambda$provide$4(MinecraftResolverImpl.java:208)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.UnsupportedOperationException: Record requires ASM8
	at org.objectweb.asm.ClassVisitor.visitRecordComponent(ClassVisitor.java:305)
	at org.objectweb.asm.ClassReader.readRecordComponent(ClassReader.java:930)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:708)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.cadixdev.bombe.asm.analysis.ClassProviderInheritanceProvider.provide(ClassProviderInheritanceProvider.java:81)
	at org.cadixdev.bombe.analysis.InheritanceProvider.provide(InheritanceProvider.java:77)
	at org.cadixdev.lorenz.model.ClassMapping.provideInheritance(ClassMapping.java:480)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.complete(InheritanceCompletable.java:83)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.complete(InheritanceCompletable.java:68)
	at org.cadixdev.lorenz.asm.LorenzRemapper.getCompletedClassMapping(LorenzRemapper.java:73)
	at org.cadixdev.lorenz.asm.LorenzRemapper.mapFieldName(LorenzRemapper.java:79)
	at org.objectweb.asm.commons.MethodRemapper.visitFieldInsn(MethodRemapper.java:150)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2421)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:721)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.cadixdev.bombe.asm.jar.JarEntryRemappingTransformer.transform(JarEntryRemappingTransformer.java:75)
	at org.cadixdev.bombe.jar.JarClassEntry.accept(JarClassEntry.java:62)
	at org.cadixdev.bombe.jar.JarClassEntry.accept(JarClassEntry.java:39)
	at org.cadixdev.atlas.jar.JarFile.lambda$transform$3(JarFile.java:188)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	... 5 more
Could not resolve: net.minecraft:server:1.18.2

> Task :prepareWorkspace UP-TO-DATE
> Task :collectNatives
> Task :downloadAssets UP-TO-DATE
> Task :genEclipseRuns
Could not resolve: net.minecraft:server:1.18.2
```

However, looking at this repo, I can see that the ASM version specified is above 8 - 9.1 at the release of version 0.2 of VanillaGradle. I have also tried 1.16.5, 1.17, and 1.17.1, all which work flawlessly.

**Comment by ThatBlockyPenguin** [comment]
How would I add this to my gradle plugins?
With this configuration:
```gradle
plugins {
    id 'java'
    id 'org.spongepowered.gradle.vanilla' version '0.2.1-SNAPSHOT'
}
```
I am getting this error:
```
* What went wrong:
Plugin [id: 'org.spongepowered.gradle.vanilla', version: '0.2.1-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.spongepowered.gradle.vanilla:org.spongepowered.gradle.vanilla.gradle.plugin:0.2.1-SNAPSHOT')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```
